apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: osdu-dag-sync-secret
  namespace: ${airflow_namespace}
spec:
  backendType: azureKeyVault
  keyVaultName: ${keyvault_name}
  data:
    - key: osdu-dag-sync-key
      name: id_rsa
      isBinary: true