apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: osdu-airflow-secret
  namespace: ${airflow_namespace}
spec:
  backendType: azureKeyVault
  keyVaultName: ${keyvault_name}
  data:
    - key: airflow-db-secret
      name: postgresql-password
      property: value
    - key: airflow-redis-secret
      name: redis-password
      property: value