apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-airflow-secret
  namespace: ${airflow_namespace}
spec:
  provider: azure
  secretObjects:
  - secretName: osdu-airflow-secret
    type: Opaque
    data:
    - objectName: redis
      key: redis-password
    - objectName: postgresql
      key: postgresql-password
    - objectName: fernetKey
      key: fernetKey  
  - secretName: osdu-az-principal
    type: Opaque
    data:
    - objectName: client-id
      key: client_id      
    - objectName: client-secret
      key: client_secret    
    - objectName: tenant-id
      key: tenant_id     
    - objectName: resource-id
      key: resource      
  - secretName: airflow-dag-sync-secret
    type: Opaque
    data:
    - objectName: dag-sync-key
      key: id_rsa                   
  parameters:
    usePodIdentity: "true"         # [OPTIONAL for Azure] if not provided, will default to "false"
    # useVMManagedIdentity: "false"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    # userAssignedIdentityID: "client_id"  # [OPTIONAL available for version > 0.0.4] use the client id to specify which user assigned managed identity to use. If using a user assigned identity as the VM's managed identity, then specify the identity's client id. If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "${keyvault_name}"          # the name of the KeyVault
    # cloudName: ""          # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    # cloudEnvFileName: ""   # [OPTIONAL available for version > 0.0.7] use to define path to file for populating azure environment
    objects:  |
      array:
        - |
          objectName: airflow-db-secret
          objectAlias: "postgresql"           # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: airflow-redis-secret
          objectAlias: "redis"
          objectType: secret
          objectVersion: ""
        - |
          objectName: osdu-az-principal-client-id
          objectAlias: "client-id"
          objectType: secret
          objectVersion: ""
        - |
          objectName: osdu-az-principal-client-secret
          objectAlias: "client-secret"
          objectType: secret
          objectVersion: ""
        - |
          objectName: osdu-az-principal-resource
          objectAlias: "resource-id"
          objectType: secret
          objectVersion: ""
        - |
          objectName: osdu-az-principal-tenant-id
          objectAlias: "tenant-id"
          objectType: secret
          objectVersion: ""
        - |
          objectName: airflow-dag-sync-key
          objectAlias: "dag-sync-key"
          objectType: secret
          objectVersion: ""
        - |
          objectName: airflow-fernetKey
          objectAlias: "fernetKey"
          objectType: secret
          objectVersion: ""
    resourceGroup: "${resource_group_name}"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "${subscription_id}"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "${tenant_id}"                 # the tenant ID of the KeyVault