# This template is responsible for debugging available variables

steps:
  - task: Bash@3
    displayName: 'Debug Variables'
    condition: eq('${{ parameters.disable }}', false)
    inputs:
      targetType: 'inline'
      script: 'env | sort'