jobs:
- job: Publish
  displayName: Copy Dependencies to Artifact Directory
  pool: $(AGENT_POOL)

  workspace:
    clean: all

  steps:
  # - task: GoTool@0
  #   displayName: 'Verify Go Version is Installed'
  #   inputs:
  #     version: '$(GO_VERSION)'
 
  # - template: tasks/lint-go.yml

  # - template: tasks/lint-tf.yml

  - task: CopyFiles@2
    displayName: Stage Pipeline Scripts
    inputs:
      contents: $(PIPELINE_ROOT_DIR)/**/*
      sourceFolder: $(Build.SourcesDirectory)
      targetFolder: $(Build.ArtifactStagingDirectory)

  # - task: CopyFiles@2
  #   displayName: Copy Terraform Directory to Artifact Directory
  #   inputs:
  #     contents: $(TF_ROOT_DIR)/**/*
  #     sourceFolder: $(Build.SourcesDirectory)
  #     targetFolder: $(Build.ArtifactStagingDirectory)

  # - task: CopyFiles@2
  #   displayName: Copy Test Harness to Artifact Directory
  #   inputs:
  #     contents: $(TEST_HARNESS_DIR)/**/*
  #     sourceFolder: $(Build.SourcesDirectory)
  #     targetFolder: $(Build.ArtifactStagingDirectory)

  - task: CopyFiles@2
    displayName: Stage Go Project Files
    inputs:
      contents: go.*
      sourceFolder: $(Build.SourcesDirectory)
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Publish the Artifact
    inputs:
      parallel: true
      parallelCount: 8
      artifactName: '$(BUILD_ARTIFACT_NAME)'
      pathToPublish: $(Build.ArtifactStagingDirectory)